# Generated by Django 5.2.5 on 2025-08-11 19:49

import verify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationattempt',
            name='captured_photo',
            field=models.ImageField(blank=True, help_text='Photo captured during verification attempt', null=True, upload_to=verify.models.verification_photo_path),
        ),
        migrations.AddField(
            model_name='verificationattempt',
            name='reference_photo',
            field=models.ImageField(blank=True, help_text="Staff's reference photo at time of verification", null=True, upload_to=verify.models.verification_photo_path),
        ),
    ]
